add the path name of enemy controlling
matias-gonz/behind-his-eyes pull request #15
Opened 2024-06-16 18:30 UTC by bytsbyts

2024-06-16 22:23 UTC, matias-gonz requested changes

2024-06-16 22:23 UTC, matias-gonz commented on Assets/KZpath1.cs
Remove file

2024-06-17 08:09 UTC, matias-gonz requested changes

2024-06-17 08:09 UTC, matias-gonz commented on KZpath1.cs
Remove file

2024-06-17 08:57 UTC, bytsbyts commented
Removed it,sorry for the late operation



---- Replied Message ----
| From | Matías Ignacio ***@***.***> |
| Date | 06/17/2024 10:09 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [matias-gonz/behind-his-eyes] add the path name of enemy controlling (PR #15) |

@matias-gonz requested changes on this pull request.

On KZpath1.cs:

Remove file

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-06-17 11:13 UTC, bytsbyts commented
I pushed new changes, can you take a look at it

2024-06-17 13:04 UTC, matias-gonz requested changes

2024-06-17 13:04 UTC, matias-gonz commented on Assets/Resources/.DS_Store
Shouldn't upload these

2024-07-07 21:17 UTC, closed without merging

2024-07-07 21:17 UTC, matias-gonz commented
Deprecated