rebuild sound mechanism
matias-gonz/behind-his-eyes pull request #32
Opened 2024-07-04 10:53 UTC by bytsbyts

with connection to individual animation

2024-07-04 12:03 UTC, matias-gonz requested changes
Nice!
Could you address the comments?
Also, we should add the script to the Player prefab

2024-07-04 12:03 UTC, matias-gonz commented on Assets/!/Scripts/PlayerAudio.cs
> +    public List<AudioClip> audioPlayer = new List<AudioClip>();
Please use `Audio` struct instead of plain `AudioClip`

2024-07-04 12:03 UTC, matias-gonz commented on Assets/!/Scripts/PlayerAudio.cs
> +    private AudioClip currentClip;
```suggestion
    private AudioClip _currentClip;

```

2024-07-04 12:03 UTC, matias-gonz commented on Assets/!/Scripts/PlayerAudio.cs
> +        // initialize audioSource
```suggestion
```

2024-07-04 12:56 UTC, bytsbyts commented on Assets/!/Scripts/PlayerAudio.cs
> +        if (currentClip != null)
All fixed now, could you check again?

2024-07-04 15:39 UTC, matias-gonz requested changes

2024-07-04 15:39 UTC, matias-gonz commented on Assets/!/Scripts/PlayerAudio.cs
> +        // Use the Find method to find the matching audio clip
These comments are redundant

2024-07-04 15:39 UTC, matias-gonz commented on Assets/!/Scripts/PlayerAudio.cs
> +    public List<Audio> audioPlayer = new List<Audio>();
We can just use an array because this will be a fixed length.
```suggestion
    public Audio[] audioPlayer;

```

2024-07-04 15:39 UTC, matias-gonz commented on Assets/!/Scripts/PlayerAudio.cs
> +        Audio? audioToPlay = audioPlayer.Find(a => a.id == clipName);
This shouldn't be nullable

2024-07-04 15:39 UTC, matias-gonz commented on Assets/!/Scripts/PlayerAudio.cs
> +        if (_currentClip != null)
Not needed since we already have a guard clause

2024-07-04 15:39 UTC, matias-gonz commented on Assets/!/Scripts/PlayerAudio.cs
> +}
missing line break

2024-07-04 15:43 UTC, matias-gonz requested changes
I can't hear crouch or crawling sounds.
Also, the walking sound is playing constantly

2024-07-04 15:58 UTC, bytsbyts commented
Crawling should work well,crouch voice is a bit low covered by walking since walking sound plays constantly.
The script I first pushed today doesn’t have the problems.
I can’t figure why it’s not working after I modified following the changes requested.
Can you help later to check on it?

| |
Claudia
|
---- Replied Message ----
| From | Matías Ignacio ***@***.***> |
| Date | 07/04/2024 下午5:43 |
| To | matias-gonz/behind-his-eyes ***@***.***> |
| Cc | bytsbyts ***@***.***>,
Author ***@***.***> |
| Subject | Re: [matias-gonz/behind-his-eyes] rebuild sound mechanism (PR #32) |

@matias-gonz requested changes on this pull request.

I can't hear crouch or crawling sounds.
Also, the walking sound is playing constantly

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-07-07 21:15 UTC, matias-gonz commented
Closed in favor of #36

2024-07-07 21:15 UTC, closed without merging