Jens dialogue smoking soldier
matias-gonz/behind-his-eyes pull request #75
Opened 2024-07-22 13:00 UTC by J3ns3its

Enemies have audio script added.
Firing sounds of k98 are triggered now from this audio Script.
Added Dialogue for first Enemy.

2024-07-22 13:12 UTC, matias-gonz requested changes

2024-07-22 13:12 UTC, matias-gonz commented on Assets/!/Scripts/EnemyAudio.cs
Please reuse the player audio, make only one script for both

2024-07-22 23:08 UTC, J3ns3its commented
I removed the script and adjusted the enemy prefab and the smoking soldier to use the player audio script

2024-07-23 07:22 UTC, matias-gonz approved these changes

2024-07-23 07:22 UTC, merged